### PR TITLE
chore: update pyproject.toml dependencies

### PR DESCRIPTION
**Pull request by dlech**
This is a couple of cleanups for pyproject.toml. See commit messages for details.

### CODE REVIEW

**Comment by bdraco** [comment]
https://github.com/Bluetooth-Devices/dbus-fast/blob/b486e3248baf7335f133ed3e67641df9a6beb091/.readthedocs.yml#L22

**Comment by dlech** [comment]
Added an alternate solution for readthedocs.org.

**Review by bdraco — APPROVED** [review]
Thanks.  LGTM

**Comment by dlech** [comment]
We could also leave the docs requirements out of `pyproject.toml` and drop [bd6ef92](https://github.com/Bluetooth-Devices/dbus-fast/pull/136/commits/bd6ef92a93ced1ea5c0969963e671be478749bcf).

**Comment by bdraco** [comment]
> We could also leave the docs requirements out of `pyproject.toml` and drop [bd6ef92](https://github.com/Bluetooth-Devices/dbus-fast/pull/136/commits/bd6ef92a93ced1ea5c0969963e671be478749bcf).

Sorry I was too quick.  Dropping them out of `pyproject.toml` works for me as well, but happy with either approach.

**Comment by dlech** [comment]
We can just leave it for now. If we get tired of updating in two places, we can consider dropping it.

**Pull request merged**
