### PR TITLE
fix: subpath bad matching

### PR DESCRIPTION
**Pull request by Mocramis**
Although uncommon, i saw nothing in the dbus spec forbidding sub-path matching possible parent paths.

Current implementation of Introspect assumes this is the case though resulting in path being presented where they are not for instance instrospect on `/a` returning subnodes `b` and `d` when the registered paths are `/a/b` and `/c/a/d` 

This mr tests and fixes the issue.

Note: a more efficient way to fix would have been to use [str.removeprefix](https://docs.python.org/3/library/stdtypes.html?highlight=removeprefix#str.removeprefix) but it is only available from python3.9.

### CODE REVIEW

**Comment by Mocramis** [comment]
Hmm i'm not sure what Codecov means by "Consider uploading the report"

**Comment by bdraco** [comment]
I think this change is fine. I would like Mike to take a look at it though since it has potential impact to supervisor

**Comment by Mocramis** [comment]
> I think this change is fine. I would like Mike to take a look at it though since it has potential impact to supervisor

Any news ?

**Comment by bdraco** [comment]
I chatted with Mike about this earlier this week. He hasn't had time to test it yet

**Comment by Mocramis** [comment]
any updates ?

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
This LGTM. I can't see this causing a problem.

**Pull request merged**
